# Generated by Django 5.0.6 on 2024-06-02 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(0, '逻辑删除'), (1, '使用中')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='cover', verbose_name='封面')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(0, '逻辑删除'), (1, '使用中')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(0, '逻辑删除'), (1, '使用中')], default=1, verbose_name='状态')),
                ('nickname', models.CharField(max_length=128, verbose_name='昵称')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('token', models.CharField(max_length=128, verbose_name='令牌')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(0, '逻辑删除'), (1, '使用中')], default=1, verbose_name='状态')),
                ('url', models.ImageField(upload_to='photo', verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfamily.album', verbose_name='所属相册')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
