# Generated by Django 5.0.6 on 2024-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfamily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='password',
            field=models.CharField(default='88888888', max_length=256, verbose_name='密码'),
        ),
    ]
